### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by Anita-ihuman** [inclusive-design/idrc#1]
## Describe the bug
The website is not responsive on mobile view

A clear and concise description of what the bug is. When the webpage is viewed on mobile it is not reponsive

## To Reproduce
Visit https://idrc.ocadu.ca/ on a mobile device

1. Go to https://idrc.ocadu.ca/

## Expected behavior
The website to be responsive on mobile

## Smartphone (please complete the following information):

- Device: iPhone7
- OS: iOS13.3.1
- Browser: safari
- Version: 13.3.1

**Comment by Anita-ihuman** [comment]
I will like to work on this issue. Please can I be assigned

**Comment by greatislander** [comment]
Hi @Anita-ihuman, we are not currently accepting community contributions to this project; we are aware of this issue and are working on it internally. Thanks for opening the issue, though!
