### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/idrc#10]
## Is your feature request related to a problem? Please describe.

We need to have a 404 page for the site, just in case.

## Describe the solution you'd like

Design and implement a custom 404 page.

## Describe alternatives you've considered

Not applicable.

## Additional context

https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

**Comment by cherylhjli** [comment]
Desktop: https://www.figma.com/proto/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=2%3A5588&viewport=932%2C475%2C0.12143322080373764&scaling=min-zoom

Mobile: https://www.figma.com/proto/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=2%3A5711&viewport=-2215%2C1190%2C0.2865554988384247&scaling=min-zoom
