### ISSUE TITLE
Second level bullets are visually indistinguishable from first level bullets

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#283]
## Describe the bug

There is no visual differentiation between bullets at different levels. For example, level 2 and level 3 bullets look the same as level 1. This makes reading lists difficult when lists should be visually formatted for nesting.

The CSS should at least indent nested lists.

Source:
![image](https://user-images.githubusercontent.com/564762/150370052-7c704cea-0e64-445d-b631-d11c2ec0a5f8.png)

What is rendered:
![image](https://user-images.githubusercontent.com/564762/150369842-27329075-1986-4679-8aa9-dd16d16c7e30.png)## Expected behavior

**Comment by Shu12388y** [comment]
Hi shubham here, I want to work on this issue can you  assign it to me

**Comment by jhung** [comment]
> Hi shubham here, I want to work on this issue can you assign it to me

Hi Shubham, thanks for being willing to help out. One of our developers is already addressing this issue.

In the future if you want to contribute to this repository I would recommend you to Fork this repository and make your changes in a branch of `dev`. Then issue a PR or make a comment to the Github issue with a link to your branch.

Feel free to look at some of the other open issues and contribute.
