### ISSUE TITLE
The ODD and IUI pages are missing the header styling

### ISSUE THREAD

**Issue by jobara** [inclusive-design/idrc#298]
## Describe the bug

The page headers for the [ODD](https://idrc.ocadu.ca/odd/) and [IUI](https://idrc.ocadu.ca/intelligent-user-interfaces-for-virtual-healthcare/) pages are just white and don't have the colours like the [EDS](https://idrc.ocadu.ca/eds/) page.

## Expected behavior

The header should have colour different from the content of the page.

## Screenshots

<img width="1523" alt="Screen Shot of ODD page header" src="https://user-images.githubusercontent.com/556024/151192597-0e7d6c6a-e09d-437c-b4f5-807871453ce0.png">
<img width="1476" alt="Screen Shot of IUI page header" src="https://user-images.githubusercontent.com/556024/151192603-e959102b-f0cb-43e7-aaca-b0aa8347aa0d.png">
<img width="1500" alt="Screen Shot of EDS page header" src="https://user-images.githubusercontent.com/556024/151192604-e0f4c169-f179-4118-8f20-eca765c1e4c4.png">

**Comment by greatislander** [comment]
See different colour configuration in the header block here:

https://github.com/inclusive-design/idrc/blob/5b9fb14a587e5e54fbe9c9738e8a83cb86e987b4/src/pages/future-of-work-equitable-digital-systems.md?plain=1#L7-L10

https://github.com/inclusive-design/idrc/blob/5b9fb14a587e5e54fbe9c9738e8a83cb86e987b4/src/pages/odd.md?plain=1#L4-L9

**Comment by jhung** [comment]
This is no longer an issue with the work done with #426 . The IUI and ODD pages are now project content with proper header area styling applied.
