### ISSUE TITLE
Some links have a yellow underline

### ISSUE THREAD

**Issue by jobara** [inclusive-design/idrc#299]
## Describe the bug

Some of the links have a yellow underline instead of black.

## To Reproduce

1. Go to the [ODD](https://idrc.ocadu.ca/odd/) page
2. In the "About" section the first link, "We Count project" has a yellow underline.

## Expected behavior

The links should have the same underline colour.

## Screenshots

<img width="530" alt="Screen Shot of the yellow and black underlined links" src="https://user-images.githubusercontent.com/556024/151193405-280c325e-d5ef-401d-a0e1-cf74347ff243.png">

**Comment by greatislander** [comment]
That's the visited style.

**Comment by jhung** [comment]
Following up on this discussion - should the style be changed so it's clear the intent? The yellow underline can be hard to see.

A dashed bottom border might be an alternative?

**Comment by jhung** [comment]
Or rather, maybe there should not be any visited style - links should always appear underlined with a solid black line. I'm not sure how important it is to communicate whether a link has been visited or not.

**Comment by chosww** [comment]
@jhung any updates on this style?

**Comment by carenwatkins** [comment]
Suggest moving all link underlines to black (text colour) and adjusting both offset and weight of the underline. Adjusting these two aspects can improve overall visual readability of paragraphs of copy. "Heavier visual weight" within a block of text can disrupt a visual reader and/or suggest the link is of greater importance even though it is not of greater importance. 

Presently on site: <img width="363" alt="Screen Shot 2023-10-26 at 2 22 10 PM" src="https://github.com/inclusive-design/idrc/assets/11746584/ac29b81b-b9d9-45f5-b0e4-74a78d7aed88">

suggested adjustment: 
<img width="528" alt="Screen Shot 2023-10-26 at 2 33 46 PM" src="https://github.com/inclusive-design/idrc/assets/11746584/fa06afe1-32d1-4ea7-9fb5-f18115da9478">
<img width="623" alt="Screen Shot 2023-10-26 at 2 35 06 PM" src="https://github.com/inclusive-design/idrc/assets/11746584/43ffc4f6-b6bd-4a66-868d-6dd7d9961c66">

**Note**: suggest the underline breaks when encountering an intersecting descender — as per existing site underline behaviour (see first image).
