### ISSUE TITLE
Scatter-plot shows outside its "box" in MS Edge

### ISSUE THREAD

**Issue by BlueSlug** [inclusive-design/idrc#30]
## Describe the bug

The scatter-plot graphic for the section with the heading "What is inclusive design?" spills outside of its container. This is only observed in Microsoft Edge 44 (so far).

## To Reproduce

1. Go to the main page of the site: https://idrc.ocadu.ca/
2. Scroll down to the 3rd section of content, with the heading "What is inclusive design?"

## Expected behavior

The scatterplot image is contained only within the blue area (as it is in other browsers)

## Screenshots

![2020-05-12 IDRC Site css bug 002](https://user-images.githubusercontent.com/547933/81743245-5e253980-946f-11ea-83c2-549a5dce9117.jpg)

## Desktop:

- OS: Windows 10 Pro v.1909
- Browser: Edge 44 (pre-Chromium)

## Additional context

This may be unintended, but it actually looks pretty cool! :)

**Comment by Raunaksingh100** [comment]
this issue FIXED closed this issue 

![closed](https://user-images.githubusercontent.com/65535360/88379026-ca9dac80-cdbf-11ea-87c5-83928901345d.PNG)

**Comment by BlueSlug** [comment]
The issue persists in Edge 44 and is not "fixed", though it may not be addressed since Chromium-based Edge is now being pushed out via Windows Update. Closing the issue is up to the project committers.
