### ISSUE TITLE
Header Section Enhancement.

### ISSUE THREAD

**Issue by grininja** [inclusive-design/idrc#33]
## Is your feature request related to a problem? Please describe.

When visiting the inclusive design research center website header section looks unattractive.the white background with little hover color change on buttons seems inappropriate and there is not much differentiation between body and header section.

## Describe the solution

The header section can be made more attractive using bootstrap and setting hovering style and buttons border and proper background.

![image](https://user-images.githubusercontent.com/60689930/83175903-4c63b780-a13a-11ea-9fe4-7d3246444928.png)

**Comment by grininja** [comment]
I want to work on this please assign this to me.

**Comment by greatislander** [comment]
@grininja Thanks for the feedback. We have decided not to use Bootstrap for this project. We are in the early stages of work on the IDRC's new website and are continuing to refine and improve the design system, and will consider your feedback in our ongoing work; if you have concrete design examples please feel free to share them.

**Comment by greatislander** [comment]
Closing this as we'll return to it in future design iterations.
