### ISSUE TITLE
H1 is larger in  whole website in mobile view (not readable)

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/idrc#40]
## Describe the bug
The size of the h1 (Which is Inclusive Design Research Centre) is two large **not readable** in  mobile view ###the name changed to be small

## To Reproduce

1. Go to 'https://idrc.ocadu.ca/'
2. Click on 'on home page'
3. in mobile view'see the size of h1 is two large'

## Screenshots before--
![idrc h1 issue](https://user-images.githubusercontent.com/65535360/88451612-997fb380-ce75-11ea-86b9-b5e7d12114f5.PNG)

### after--
![issue fixed h1](https://user-images.githubusercontent.com/65535360/88451666-1d39a000-ce76-11ea-9fe6-a78d8005b9b2.PNG)

## Smartphone (please complete the following information):

- Device: [e.g. iPhone 5 ,5s ,6 ]
- Browser [e.g. stock browser]

## Additional context
i already fixed this issue for all the devices added just media query for this here the link of my pr #39 
@cindyli @greatislander @gtirloni

**Comment by greatislander** [comment]
This will be addressed as the design system is developed and implemented (see: https://github.com/inclusive-design/idrc/projects/2#card-42813694).
