### ISSUE TITLE
h1 overlapping to right in galaxy fold

### ISSUE THREAD

**Issue by Raunaksingh100** [inclusive-design/idrc#42]
## Describe the bug
the problem of h1 in mobile view overlapping to right and also not readable...........

1. Go to this direct link  'https://idrc.ocadu.ca/vision-technology-service/'
3. Switch to galaxy fold screen 

## Expected behavior
this h1 problem in the whole website 

### Screenshots before---
![idrc](https://user-images.githubusercontent.com/65535360/89736033-449e8880-da84-11ea-8203-bd9bc4306db2.PNG)

### after-
![idrc fixed](https://user-images.githubusercontent.com/65535360/89736041-51bb7780-da84-11ea-81cf-921e2af481ae.PNG)

## Smartphone (please complete the following information):

- Device: [e.g. galaxy fold]
- Browser [e.g. stock browser]

## Additional context
@greatislander

**Comment by Raunaksingh100** [comment]
@greatislander  i make pr for this  h1 on ### 19 july 2020 for [MOBILE VIEW]   but you close this 
so can you tell me  can i create pr for this what is the proper h1 size you want to do so can i able to create a pr for this

**Comment by greatislander** [comment]
@Raunaksingh100 I don't think you read my comment on the previous issue; we will be looking at the type system as a whole in upcoming work and I don't want to make small changes until we've taken a broader look. Thanks for understanding.
