### ISSUE TITLE
For Page content types, the preview pane contains information that should be hidden

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#451]
## Describe the bug

The preview pane for Pages content type contains information that are irrelevant to the user and should probably be hidden. For example, the header border, background, and text colour are written out in the preview as:
```
    indigo-100
    indigo-100
    black
```

The Preview pane should only include content that is going to be displayed on the site.

## To Reproduce

1. Go to Pages > select "New Page"
2. Open the preview pane
3. Notice that the preview pane contains text ("indigo-100" etc.) that has not been entered into the form.

## Expected behavior

The preview pane should only display the content entered on the form.

## Screenshots

![image](https://user-images.githubusercontent.com/564762/205377075-01dc6aa2-0bd5-4a5b-8a4f-f7dc01906436.png)

**Comment by jhung** [comment]
Looks like this might be an issue in other content types as well. For example, the short name for a Project appears in the preview.

**Comment by cindyli** [comment]
Resolved with the merge of https://github.com/inclusive-design/idrc/issues/459
