### ISSUE TITLE
On the Projects page project images should not stretch 100% width by default

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#453]
## Is your feature request related to a problem? Please describe.

On the projects page, an image in the content should not stretch 100% of the width by default. This is a problem when uploading images like logos at a smaller resolution which then get stretched horizontally and scaled vertically. The result is a image that appears really big on the screen.

Currently users are working around this issue by creating really wide images with empty horizontal space so the width scaling does not oversize the image.

## Describe the solution you'd like

For the Projects page, the image width styling should be `auto` and not `100%`.

```
.page--projects-and-tools article img {
   width:auto;
}
```

## Additional context

![image](https://user-images.githubusercontent.com/564762/206001050-ae0e1eb9-4aad-4aa0-a91f-da847b160ee4.png)
Above a logo as seen currently with `width: 100%;`

![image](https://user-images.githubusercontent.com/564762/206001190-f2703ece-7a9b-4bcb-9ce6-758093eddcd1.png)
Above: a logo as seen with `width: auto;`

**Comment by cindyli** [comment]
This issue should have been resolved with the implementation of a new CMS editor component "Image Position with Text", merged at https://github.com/inclusive-design/idrc/commit/514c79658923bb3751514204ed22744c6c57dac5
