### ISSUE TITLE
Add eleventy-plugin-sharp for image processing

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/idrc#46]
## Is your feature request related to a problem? Please describe.

We should scaled down uploaded images to appropriate responsive sizes so that users don't have to manage multiple image sizes through the CMS.

## Describe the solution you'd like

Add [eleventy-plugin-sharp](https://github.com/luwes/eleventy-plugin-sharp) to the Eleventy configuration to handle image resizing.

## Describe alternatives you've considered

Not applicable.

## Additional context

[@11ty/eleventy-img](https://github.com/11ty/eleventy-img/) does not currently [support cropping](https://github.com/11ty/eleventy-img/pull/10). [eleventy-plugin-sharp](https://github.com/luwes/eleventy-plugin-sharp) involves more configuration via filters in templates but supports cropping and scaling.

**Comment by rishhabh-jain** [comment]
Hey, I want to work on this issue. How can I do that

**Comment by greatislander** [comment]
@rishhabh-jain thanks for your interest! However, this issue involves close collaboration within our team working on design and development and as such is not a good candidate for open source contributions. I will be adding the `good first issue` tags to issues where external contributions are encouraged.
