### ISSUE TITLE
Resizing the projects page narrow distorts project thumbnails

### ISSUE THREAD

**Issue by jhung** [inclusive-design/idrc#498]
## Describe the bug

If the client is sufficiently narrow, project thumbnails may stretch vertically distorting the thumbnail.

## To Reproduce

1. Go to 'https://idrc.ocadu.ca/projects-and-tools/`
2. Shrink client window until it's almost mobile layout.
3. notice how the thumbnails get squished and distorted

## Screenshots
![image](https://user-images.githubusercontent.com/564762/222285103-e0c4b7fa-c6df-45c7-a03f-8d72d9524d32.png)

**Comment by jobara** [comment]
You might be able to use css [aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) property. According to [caniuse](https://caniuse.com/?search=aspect-ratio) it has good modern support.
