### ISSUE TITLE
Some text did not get increased when increasing the text size from  the preferences.

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/idrc#5]
## Describe the bug
Some text did not get increased when increasing the text size from the preferences.
they are located at the right bottom side of the page inside the boxes whose headings are.
- IDRC @idrc_ocadu
- Fluid Project @FluidProject
- SNOW @SNOWocad

## To Reproduce

1. Change the size of the text in preperences
2. see error

## Screenshots
![Screenshot (198)](https://user-images.githubusercontent.com/30374226/78184760-9fe1be00-7487-11ea-9935-caceb6e0d85c.png)

## Desktop (please complete the following information):

- OS: [e.g. windows 10]
- Browser [e.g. chrome]

**Comment by greatislander** [comment]
Hi @Chaitanyassr, this is not the correct repository for the current website. That website is at https://github.com/inclusive-design/idrc.ocad.ca.

**Comment by Chaitanyassr** [comment]
> Hi @Chaitanyassr, this is not the correct repository for the current website. That website is at https://github.com/inclusive-design/idrc.ocad.ca.

Okay thank you... i will report there.
