### ISSUE TITLE
Reorder projects in projects page

### ISSUE THREAD

**Issue by chosww** [inclusive-design/idrc#579]
## Is your feature request related to a problem? Please describe.

Some projects should be displayed first based on their importance and updated dates. 

Here's the order:

1. We Count

2. Weavly

3. Community-Led Co-design Kit

4. Data Communities for Inclusion (DCI)

5. Ecocultural Mapping Project

6. Learning to Be Human Together (Humanizing Learning)

7. The Accessibility Exchange (TAE)

8. Flexible Learning for Open Education (FLOE)

9. Our Doors Are Open

10. Future of Work: Equitable Digital Systems (EDS)

11. Future of Work and Disability (FWD)

12. Communication Access Within the Accessible Canada Act

13. Coding to Learn and Create

14. Platform Co-op Development Kit

15. Social Justice Repair Kit

16. Centre on Inclusive Software for Learning (CISL)

17. Inclusive Cities

18. Optimizing Diversity with Disability

19. Intelligent User Interfaces for Virtual Healthcare

**Comment by cindyli** [comment]
@carenwatkins is in the process of editing "Communication Access Within the Accessible Canada Act" project page. She noticed this page is moved to the bottom of the project list. See the screenshot below. [The order value](https://github.com/inclusive-design/idrc/blob/dev/src/projects/communication-access-within-the-accessible-canada-act.md) of this page remains unchanged at 65.

@chosww, can you investigate why this is happening when you have time? Thanks.

<img width="411" alt="Screenshot 2023-04-26 at 11 01 48 AM" src="https://user-images.githubusercontent.com/572877/234618463-771821b2-f233-4d0e-8285-752d6721aca9.png">

**Comment by chosww** [comment]
Hey @cindyli, I just checked commit logs in main branch, and the order of the project has changed to 110: https://github.com/inclusive-design/idrc/commit/20688b6c405115afbb4d2818d264b18608304467, and that's why the project is sitting at the bottom.

**Comment by chosww** [comment]
I am unsure what has caused the change in the order; I updated the project through the authoring interface in local environment, and the order remains the same.
