### ISSUE TITLE
Clicking an option from "color and contrast" of preferences makes the whole preference section dragged back to initial position.

### ISSUE THREAD

**Issue by Chaitanyassr** [inclusive-design/idrc#6]
## Describe the bug
Clicking an option from "color and contrast" of preferences makes the whole preference section dragged back to initial position. We have horizontal  scroll bars for preference section. When clicking the option from color and contrast reset the horizontal scroll bar position to initial. While it does not happened with other options like "table of content" or "link and buttons".
It also did not happened in Fluid and FLOE project website.

## To Reproduce

1. Go to preferences
2. Click any option from color and contrast
3. See error

- Browser [e.g. chrome]

**Comment by greatislander** [comment]
i @Chaitanyassr, this is not the correct repository for the current website. That website is at https://github.com/inclusive-design/idrc.ocad.ca.
