### ISSUE TITLE
About: update links from home page

### ISSUE THREAD

**Issue by greatislander** [inclusive-design/idrc#83]
## Is your feature request related to a problem? Please describe.

Currently some links from the home page, which should link to various pages under about, point elsewhere. For example, "What is Inclusive Design?" should link to "About / Philosophy".

## Describe the solution you'd like

We need to assess parts of the home page that should be linked to about pages now that they exist.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by cherylhjli** [comment]
Instead of having all of those links under the "what is inclusive design" section, we can have one link - "learn more about our philosophy" that links to about > philosophy. This is now reflected on the home page mockups.

Are there other links we need to take care of in relation to the about page?

**Comment by greatislander** [comment]
@cherylhjli I was thinking the very top section should have a link (at the bottom) to History, maybe?

**Comment by cherylhjli** [comment]
Ah! I can definitely see a "learn more about us" to the overview page. That could provide enough of an overview, and then people can dive deeper into the full on history if they want - unless I'm missing another reason to link to history from the top of the home page?

**Comment by greatislander** [comment]
It's the "Established in 1993" that makes me think of a link to History but yeah, Overview probably makes more sense.
